### ISSUE TITLE
Replace ineffective political CoC

### ISSUE THREAD

**Issue by Wisdometrics** [GDquest/make-pro-2d-games-with-godot#103]
I've noticed the project uses the Contributor Covenant code of conduct. I believe it was added in good faith but I would like to highlight several examples of its misuse due to its vague and political nature:

**Opal**, attempt to witch-hunt dev out of the project over personal opinion thwarted by maintainer being open-minded: https://github.com/opal/opal/issues/941

The entire **GitHub** Code of Conduct Drama: http://archive.is/JzOoj https://www.reddit.com/r/linux/comments/3g8ehh/github_puts_open_code_of_conduct_on_pause_cites/

**Django** attempt to impose "Contributor Covenant" over project for rejected pull requests from "People of Color", then labeling him an ist and saying they'll go to management: https://archive.is/dgilk
>As a suggestion I recommend adopting the Contributor Code of Conduct to ensure everybody's contributions are accepted regarless of their sex, sexual orientation, skin color, religion, height, place of origin, etc, etc, etc. As a white straight male and lead of this trending repository, your adoption of this Code of Conduct will send a loud and clear message that inclusion is a primary objective of the Django community and of the software development community in general.

**Ruby** attempt to impose the Contributor Covenant over the project, founder Matz thankfully aware enough to reject it, here's his explanation: https://bugs.ruby-lang.org/issues/12004#note-95
Following that attempts by Contributor Covenant to get Matz separated from "Community Management": https://twitter.com/CoralineAda/status/690334282607378432 and insults year later: https://twitter.com/CoralineAda/status/1029170073938944000
Thankfully he knows what's up: https://twitter.com/CoralineAda/status/1041701099378540544

**PHP** attempt to impose Contributor Covenant on the project that thankfully fails after a few skirmishes and a few great explanations why: http://paul-m-jones.com/archives/6214
>the Contributor Covenant, and any other codes of conduct originating in Social Justice, are to be opposed out of hand, both in PHP, and in any other place they are suggested

**Node.js** attempt to remove a contributor over sharing an article on Twitter: https://quillette.com/2017/07/18/neurodiversity-case-free-speech/
http://archive.is/h6lem
>Most recently Rod tweeted in support of an inflammatory anti-Code-of-Conduct article. As a perceived leader in the project, it can be difficult for outsiders to separate Rod’s opinions from that of the project. Knowing the space he is participating in and the values of our community, Rod should have predicted the kind of response this tweet received.

After lengthy attempts to defend himself: https://medium.com/@rvagg/the-truth-about-rod-vagg-f063f6a53557 he barely survives a vote triggered to throw him out of the project, activists are pissed: https://twitter.com/ag_dubs/status/899749156209664000
After the Kangoroo court is over, people point out said activists broke said "Code of Conduct" in much more severe ways, no action is taken: http://archive.is/7cL5s

**Drupal** contributor is thrown out of the project for his personal sex life: https://www.inc.com/sonya-mann/drupal-larry-garfield-gor.html after activists in its "Diversity & Inclusion group" set up dozen pages political dossier of supposedly "problematic" comments he might have made on Twitter/Reddit or his Blog: https://www.scribd.com/document/350215190/Crell

This is what this and similar "Code of Conducts" are designed to do, and [explicitly so by its creator](https://twitter.com/CoralineAda/status/1041465346656530432). Create political Drama and arguments and get outside activists to start witch-hunts and Social media/media s*itstorms against developers with private political opinions they dislike.

They're also implicitly anti-meritocratic and such language was embedded within the first versions of it, for instance "pervasive cult of meritocracy": https://twitter.com/dashorst/status/534473049647898624 and even if it's not explicit anymore, the intent of its creator is clear: https://postmeritocracy.org/

source: https://www.reddit.com/r/linux/comments/9hazny/linus_talked_to_the_new_yorker_about_verbal_abuse/e6azknp/

Here are some alternative CoCs which are far less ambiguous and do not have such a horrible track record:  
https://kde.org/code-of-conduct/  
https://www.gnu.org/philosophy/kind-communication.html  
https://www.ruby-lang.org/en/conduct/
None at all. CoCs are introduced to communities where disrespect and harassment is rampant and this is not what I see in the Godot community. Godot itself does not have a CoC.

**Comment by NathanLovato** [comment]
Actually, no, we don't use them, i just forgot to remove the file, thanks: https://www.gdquest.com/open-source/guidelines/kind-communication-guidelines/
