### ISSUE TITLE
Please add a hacktoberfest topic.. please

### ISSUE THREAD

**Issue by CODERman11** [GDquest/make-pro-2d-games-with-godot#109]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Bug report ##

**What is the current behavior?**

**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by CODERman11** [comment]
please add a hacktoberfest topic

**Comment by NathanLovato** [comment]
Same reply as https://github.com/GDQuest/godot-demos/issues/73
