### ISSUE TITLE
Can not run the project with Godot 3.1 alpha or the master branch

### ISSUE THREAD

**Issue by Liangdi** [GDquest/make-pro-2d-games-with-godot#86]
Version: 3.1.alpha.official 
System: Fedora 28 x86_64

![selection_094](https://user-images.githubusercontent.com/1019161/47668585-cbea7700-dbe3-11e8-893f-7f79b74521c6.png)
![selection_095](https://user-images.githubusercontent.com/1019161/47668584-cb51e080-dbe3-11e8-94f1-64a88b261cb4.png)

Also can not run with 3.0.6 stable, with the output:
```
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OPENING: /home/liangdi/git/godot/make-pro-2d-games-with-godot (::home::liangdi::git::godot::make-pro-2d-games-with-godot)
ERROR: _load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN
   At: core/project_settings.cpp:495.
ERROR: _load_settings_text_or_binary: Couldn't load file '/home/liangdi/git/godot/make-pro-2d-games-with-godot/project.godot', error code 12.
   At: core/project_settings.cpp:519.
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
```

**Comment by Zireael07** [comment]
Did you try running it with 3.1 first? In that case, 3.0.6 won't open it.

**Comment by Liangdi** [comment]
> Did you try running it with 3.1 first? In that case, 3.0.6 won't open it.

yes ...  i try again , it is the reason , so , it is not a issue now ... thanks
