### ISSUE TITLE
can't use get_node() with absolute paths from outside the active scene tree

### ISSUE THREAD

**Issue by hanxuechen** [GDquest/make-pro-2d-games-with-godot#96]
![image](https://user-images.githubusercontent.com/31240078/55134865-0c372c80-5165-11e9-91b1-a7dc8fead744.png)
can't use get_node() with absolute paths from outside the active scene tree
what does this possibly means?

**Comment by NathanLovato** [comment]
I'll need more information to know what triggers that. I haven't checked the project in 3.1 stable yet.

**Comment by hanxuechen** [comment]
hey, sorry for late, perhaps i could older version to fire up. this error occur without anything change. i just import and F6.
