### ISSUE TITLE
Port to Godot 3.1

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/make-pro-2d-games-with-godot#97]
Godot 3.1 doesn't support different function signatures when you override a method. E.g.

```gdscript
# Menu.gd
func initialize(args=[]):
```

Overriding it as

```gdscript
# ShopMenu.gd
extends Menu.gd

func initialize(shop, buyer, items):
```

Will give this error:

```Parser Error: Function signature doesn't match the parent. Parent signature is: 'Variant initialize(Variant=default)'.```

**Comment by rhasce** [comment]
yea same

**Comment by NathanLovato** [comment]
Done with c2133ce124ec16f875be29bc36065e2fcab9cecf, although a handful of bugs are left on the UI front
